<a href="https://colab.research.google.com/github/bcrbandung/project/blob/main/manipulating_table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
url = 'https://raw.githubusercontent.com/bcrbandung/project/main/googleplaystore.csv'

In [13]:
df = pd.read_csv(url, encoding='unicode_escape')
df.head(2)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up

# **MENGABUNGKAN 2 TABEL**

df_output = pd.merge(df.drop_duplicates(), 
                      region, 
                      on ='warehouse',
                      how ='left')


df_output

left_join = pd.merge(sales, 
                      customer, 
                      left_on ='customer_id', 
                      right_on = 'ID',
                      how ='left')

# **Export CSV**

apps_education 
path = 'gdrive/MyDrive/dataset/'
df.to_csv(path+"latihan_export.csv", index=None)

path = 'gdrive/MyDrive/dataset/'
df.to_csv(path+"latihan_export.xlsx", index=None)

writer = pd.ExcelWriter('database_customer.xlsx', engine='xlsxwriter')
aceh.to_excel(writer, sheet_name='ACH', index=False)
ambon.to_excel(writer, sheet_name='AMB', index=False)
bali.to_excel(writer, sheet_name='BAL', index=False)
writer.save()

In [5]:
from google.colab import drive

In [6]:
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

In [8]:
path = 'gdrive/MyDrive/dataset/'
df.to_csv(path+"latihan_export.csv", index=None)

# **Mengganti Label Kolom**

correction = correction.rename(columns={"Customer_id":"customer_id"})
hasil_mapping_all = hasil_mapping_all.rename(columns={"customer_x":"customer", "1":"Jan", "2":"Feb", "3":"Mar", "4":"Apr", "5":"May", "6":"Jun", "7":"Jul", "8":"Aug", "9":"Sep", "10":"Oct" })

In [14]:
df_correction = df.rename(columns={"App":"Application", "Genres":"Genre"})
df_correction.head(2)

,Application,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genre,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up

# **Menghilangkan beberapa kolom**


correct_region = correct_region.drop(['Sales Area', 'Customer'], axis=1)

In [15]:
df_correction_drop = df_correction.drop(['Type', 'Price'], axis=1)
df_correction_drop.head(2)

,Application,Category,Rating,Reviews,Size,Installs,Content Rating,Genre,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up

# **Sorting Value dari sebuah kolom**

correct_region = correct_region.sort_values('Area Sales')

In [17]:
df_correction_sort = df_correction.sort_values('Reviews')
df_correction_sort.head(5)

,Application,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genre,Last Updated,Current Ver,Android Ver
5499,AQ SMS Notify,TOOLS,NaN,0,2.3M,10+,Free,0,Everyone,Tools,"April 12, 2018",2.5.3,4.1 and up
6738,BS Chopper,GAME,NaN,0,41M,100+,Free,0,Everyone,Racing,"October 5, 2017",1.0,4.1 and up
4177,G-NetReport Pro,TOOLS,NaN,0,1.6M,10+,Paid,$25.99,Everyone,Tools,"June 14, 2018",5.0,4.0 and up
6399,Of the wall Arapaho bk,COMMUNICATION,NaN,0,12M,5+,Free,0,Everyone,Communication,"August 18, 2017",1.0,4.1 and up
9532,Ek-yatri: Travel where you Belong,TRAVEL_AND_LOCAL,NaN,0,29M,1+,Free,0,Everyone,Travel & Local,"August 1, 2018",1.0.0,4.4 and up

# **Create 2 List**

from  itertools import product
import pandas as pd
df = pd.DataFrame(product(list_dc, sku), columns = ['list_dc','sku'])
df

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

# **Slicing/ Memilih menampilkan baris tertentu**

In [21]:
df[2:5]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2,"U Launcher Lite â FREE Live Cool Themes, Hid...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

# **DROP DUPLICATE**


customer = customer.drop_duplicates(subset='ID', keep='last')

# **Menghitung Nilai Unique**
sales['customer_id'].drop_duplicates().count()

# **Menampilkan Nilai Unique**
gapminder['country'].unique()

In [26]:
df_drop_duplicate = df.drop_duplicates(subset='Category', keep='last')
df_drop_duplicate.head(4)
df_drop_duplicate['Reviews'].count()

34

#  Menghilangkan Kolom dengan nama akhiran tertentu

ach_sr.drop(ach_sr.filter(regex='_y$').columns.tolist(),axis=1, inplace=True)

# **Mengganti Nilai dalam 1 kolom**


sales['brand'] = sales['brand'].replace(['OMG OH MY GLAM'],['OMG'])

correction['RSO'] = correction['RSO'].replace(['RSO 1','RSO 2'],['AREA JAKARTA 2','AREA JAKARTA 1'])

In [33]:
df_drop_duplicate['Type'] = df_drop_duplicate['Type'].replace(['Free'],['Gratis'])
df_drop_duplicate.head(4)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
854,Toca Life: Hospital,EDUCATION,4.7,3528,24M,"100,000+",Paid,$3.99,Everyone,Education;Pretend Play,"June 12, 2018",1.1.1-play,4.4 and up
1003,Colorfy: Coloring Book for Adults - Free,ENTERTAINMENT,4.5,787177,Varies with device,"10,000,000+",Gratis,0,Everyone,Entertainment,"June 20, 2018",Varies with device,Varies with device
8888,Spring flowers theme couleurs d t space,ART_AND_DESIGN,5.0,1,2.9M,100+,Gratis,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up
9311,StudyLock - Education First,PARENTING,4.1,27,4.6M,"1,000+",Gratis,0,Everyone,Parenting,"October 12, 2017",1.13,4.1 and up

# **Pivoting:**

pivot = sales.groupby(['sales_area','brand']).sum()

data = data.pivot_table(
        values='do_rp', 
        index=['customer_id', 'customer', 'channel_report', 'sub_channel', 'outlet_type_report'], 
        columns='month', 
        aggfunc=np.sum)

In [40]:
pivot = df_drop_duplicate.groupby(['Genres','Type']).sum()
pivot.head(2)

                        Rating
Genres          Type
Art & Design    Gratis     5.0
Auto & Vehicles Gratis     0.0

# **CONCAT antara 2 kolom**


pivot['col_gab'] = pivot.sales_area.str.cat(pivot['brand'])

In [42]:
df_drop_duplicate ['kolom_gabungan'] = df_drop_duplicate.App.str.cat(df_drop_duplicate['Category'])
df_drop_duplicate.head(2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,kolom_gabungan
854,Toca Life: Hospital,EDUCATION,4.7,3528,24M,"100,000+",Paid,$3.99,Everyone,Education;Pretend Play,"June 12, 2018",1.1.1-play,4.4 and up,Toca Life: HospitalEDUCATION
1003,Colorfy: Coloring Book for Adults - Free,ENTERTAINMENT,4.5,787177,Varies with device,"10,000,000+",Gratis,0,Everyone,Entertainment,"June 20, 2018",Varies with device,Varies with device,Colorfy: Coloring Book for Adults - FreeENTERT...

# **Mengubah Urutan Kolom**

kolom = list(pivot.columns)
kolom[5],kolom[6] = kolom[6],kolom[5]
kolom

In [50]:
list_column= list(df_drop_duplicate.columns)
list_column[1], list_column[13] = list_column[13], list_column[1]
list_column

['App',
 'kolom_gabungan',
 'Rating',
 'Reviews',
 'Size',
 'Installs',
 'Type',
 'Price',
 'Content Rating',
 'Genres',
 'Last Updated',
 'Current Ver',
 'Android Ver',
 'Category']

In [79]:
df_drop_duplicate_urutanbaru = df_drop_duplicate[list_column]
df_drop_duplicate_urutanbaru.head(4)

,App,kolom_gabungan,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Category
854,Toca Life: Hospital,Toca Life: HospitalEDUCATION,4.7,3528,24M,"100,000+",Paid,$3.99,Everyone,Education;Pretend Play,"June 12, 2018",1.1.1-play,4.4 and up,EDUCATION
1003,Colorfy: Coloring Book for Adults - Free,Colorfy: Coloring Book for Adults - FreeENTERT...,4.5,787177,Varies with device,"10,000,000+",Gratis,0,Everyone,Entertainment,"June 20, 2018",Varies with device,Varies with device,ENTERTAINMENT
8888,Spring flowers theme couleurs d t space,Spring flowers theme couleurs d t spaceART_AND...,5.0,1,2.9M,100+,Gratis,0,Everyone,Art & Design,"April 18, 2018",1.0.2,4.0 and up,ART_AND_DESIGN
9311,StudyLock - Education First,StudyLock - Education FirstPARENTING,4.1,27,4.6M,"1,000+",Gratis,0,Everyone,Parenting,"October 12, 2017",1.13,4.1 and up,PARENTING

# **SPLIT DATA menjadi beberapa file Excel**

jakarta1 = sales['sales_area'] == 'JAKARTA 1'
jakarta2 = sales['sales_area'] == 'JAKARTA 2'
bogor = sales['sales_area'] == 'BOGOR'

jakarta1 = sales[jakarta1]
jakarta2 = sales[jakarta2]
bogor = sales[bogor]

jakarta1.to_excel(r'C:\Users\juprisupriadi\Documents\cloud\daily_sales_jakarta1.xlsx', index = False)
jakarta2.to_excel(r'C:\Users\juprisupriadi\Documents\cloud\daily_sales_jakarta2.xlsx', index = False)
bogor.to_excel(r'C:\Users\juprisupriadi\Documents\cloud\daily_sales_bogor.xlsx', index = False)

In [53]:
df_drop_duplicate_urutanbaru['Category'].unique()

array(['EDUCATION', 'ENTERTAINMENT', 'ART_AND_DESIGN', 'PARENTING',
       'BEAUTY', 'FOOD_AND_DRINK', 'HOUSE_AND_HOME', '1.9',
       'TRAVEL_AND_LOCAL', 'DATING', 'LIBRARIES_AND_DEMO', 'PHOTOGRAPHY',
       'SHOPPING', 'HEALTH_AND_FITNESS', 'EVENTS', 'SPORTS',
       'PERSONALIZATION', 'COMMUNICATION', 'GAME', 'AUTO_AND_VEHICLES',
       'TOOLS', 'FINANCE', 'PRODUCTIVITY', 'VIDEO_PLAYERS', 'SOCIAL',
       'COMICS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION', 'WEATHER',
       'BUSINESS', 'FAMILY', 'MEDICAL', 'BOOKS_AND_REFERENCE',
       'LIFESTYLE'], dtype=object)

In [58]:
education = df['Category'] == 'EDUCATION'
entertainment = df['Category'] == 'ENTERTAINMENT'
parenting = df['Category'] == 'PARENTING'

In [60]:
apps_education = df[education]
apps_entertainment = df[entertainment]
apps_parenting = df[parenting]

In [65]:
path = 'gdrive/MyDrive/dataset/'
apps_education.to_csv(path+"apps_edu.xlsx", index=None)

In [67]:
!pip install xlsxwriter 
# writer = pd.ExcelWriter('database_customer.xlsx', engine='xlsxwriter') 
# aceh.to_excel(writer, sheet_name='ACH', index=False) 
# ambon.to_excel(writer, sheet_name='AMB', index=False) 
# bali.to_excel(writer, sheet_name='BAL', index=False) writer.save()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting xlsxwriter
  Downloading XlsxWriter-3.0.3-py3-none-any.whl (149 kB)
     |████████████████████████████████| 149 kB 5.2 MB/s
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.0.3

In [74]:
writer = pd.ExcelWriter('application.xlsx', engine='xlsxwriter') 
apps_education.to_excel(writer, sheet_name= 'EDU', index=False)
apps_entertainment.to_excel(writer, sheet_name= 'ENT', index=False)
apps_parenting.to_excel(writer, sheet_name= 'PAR', index=False)
writer.save()

# **Mengisi data yang NA dengan nol**

data = data.fillna(0)